### PR TITLE
Feature/hzc 2039 sql with json

### PR DESCRIPTION
**Pull request by ivan-shevtsov**
Added java client that creates 2 Maps (Country and City) with value of type Json, then creates SQL Mapping and executes some queries with filtering and joining of these two Maps

### CODE REVIEW

**Review by huseyinbabal — CHANGES_REQUESTED** [review]
@ivan-shevtsov could you please coordinate with @sdreger, since we shouldn;t introduce a second main class, the entrypoint of examples should be in Client.java or ClientWithSsl.java.  See example here https://github.com/hazelcast/hazelcast-cloud-java-sample-client/blob/781a6a303372590ac9832d7ff10c083b48fad9bf/src/main/java/com/hazelcast/cloud/Client.java#L36

**Comment by huseyinbabal** [comment]
@ivan-shevtsov I am getting following example during example execution on my local, any idea?
```
com.hazelcast.sql.HazelcastSqlException: Unsupported serialization format: json-flat
    at com.hazelcast.sql.impl.client.SqlClientService.handleResponseError (SqlClientService.java:276)
    at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse (SqlClientService.java:135)
    at com.hazelcast.sql.impl.client.SqlClientService.lambda$execute$0 (SqlClientService.java:108)
    at com.hazelcast.internal.util.ExceptionUtil.lambda$withTryCatch$1 (ExceptionUtil.java:207)
    at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture$CallIdTrackingBiConsumer.accept (ClientInvocationFuture.java:268)
    at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0 (AbstractInvocationFuture.java:1563)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec (ForkJoinTask.java:1426)
    at java.util.concurrent.ForkJoinTask.doExec (ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec (ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan (ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker (ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run (ForkJoinWorkerThread.java:183)```

**Comment by ivan-shevtsov** [comment]
I have just retested with Basic hz 5.0 and it works ok. 
image

**Comment by sdreger** [comment]
@ivan-shevtsov : Just checked the latest changes with this cluster:

image

And looks like everything works fine:
```
Dec 01, 2021 12:55:10 PM com.hazelcast.client.impl.spi.ClientClusterService
INFO: hz.client_1 [ba-46452] [5.0]

Members [1] {
	Member [10.181.4.90]:34378 - 7818ba7c-d150-4398-ab33-966333b6c2f0
}

Dec 01, 2021 12:55:11 PM com.hazelcast.client.impl.statistics.ClientStatisticsService
INFO: Client statistics is enabled with period 5 seconds.
Connection Successful!
Mapping for countries has been created
Populate Countries with map - values as JSON
--------------------
Select all countries with sql = SELECT c.country from country c
country=United States
country=Czech Republic
country=England
country=Australia
--------------------
Populate cities
Mapping for cities has been created
--------------------
Select city and population with sql = SELECT city, population FROM city where country=?
city=Canberra, population=354644
--------------------
Select country and city data in query that joins tables
 iso |         country |                 city |      population |
  US |   United States |       Washington, DC |          601723 |
  US |  Czech Republic |       Washington, DC |          601723 |
  EN |         England |               London |         8174100 |
  AU |       Australia |             Canberra |          354644 |
--------------------
```

@huseyinbabal could you check your cluster version, and if it's recent 5.x - please check it again, it should work.

**Review by sdreger — APPROVED** [review]

**Review by huseyinbabal — APPROVED** [review]
Works as expected thanks

Screen Shot 2021-12-02 at 14 23 30
Screen Shot 2021-12-02 at 14 23 38

**Pull request merged**
